positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://contLOK:3100/loki/api/v1/push

scrape_configs:
  - job_name: api_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          __path__: /var/log/fastapi/*.log